version: 0.0.1-{build}

environment:
  PYTHON_VERSION: 3.4
  MINICONDA: C:\Miniconda3

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n scimpy-environment python=%PYTHON_VERSION% numpy scipy matplotlib pandas pip"
  - activate scimpy-environment
  - pip install pyaudio pyinstaller
  - curl -L -o upx.zip http://libgd.blob.core.windows.net/upx/upx391w.zip
  - 7z e upx.zip *.exe -r
  - curl -L -o tbb.zip https://github.com/01org/tbb/releases/download/4.4.5/tbb44_20160526oss_win.zip
  - 7z e tbb.zip tbb44_20160526oss/bin/ia32/vc10/*.dll

build_script:
  - "echo %PATH%"
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - activate scimpy-environment
  - pyinstaller run.py --noupx -n scimpy_win32_%APPVEYOR_BUILD_VERSION% --distpath scimpy_win32_%APPVEYOR_BUILD_VERSION%
  - .\upx.exe --lzma scimpy_win32_%APPVEYOR_BUILD_VERSION%/scimpy_win32_%APPVEYOR_BUILD_VERSION%/*.exe scimpy_win32_%APPVEYOR_BUILD_VERSION%/scimpy_win32_%APPVEYOR_BUILD_VERSION%/*.dll
  - cp LICENSE* scimpy_win32_%APPVEYOR_BUILD_VERSION%/scimpy_win32_%APPVEYOR_BUILD_VERSION%

artifacts:
  - path: scimpy_win32_%APPVEYOR_BUILD_VERSION%

only_commits:
  message: /\[build\]/
